### ISSUE TITLE
Farming Habitat and Synth Ascension 

### ISSUE THREAD

**Issue by VernMcC** [OldEnt/stellaris-habitat-start-amaryllis#3]
I built a farm habitat while I was completing the Synth, it finished after ascension was completed.I noticed that the farm districts would appear and disappear. Looking at the code it appears this is due to the test for whether I am using food. Whenever I have organic pops assimilating, the farm districts show up and I even completed a build of one, but if at any time I stop using food (all assimilated before fresh pops arrive) I lose access to the districts and when they do show up, the completed district was gone.

**Comment by OldEnt** [comment]
Oh, right. This check shouldn't take place on a *Farming* Arcology as it defeats the purpose. [I removed the relevant lines](https://github.com/OldEnt/stellaris-habitat-start-amaryllis/commit/36b93d987792bc20cd5ab9a71f0207ced092bd73). The update is now uploaded and available on Steam and Paradox Plaza. Have a go and let me know if that fixed it for you. Thanks for the report!

**Comment by OldEnt** [comment]
I should probably account for synthetic ascension perk in the decisions file as well (possible arcology projects). Will do this soon.

EDIT: [done](https://github.com/OldEnt/stellaris-habitat-start-amaryllis/commit/9bbfda61f2b5871f540a08734302c68f58bcdab3)

**Comment by OldEnt** [comment]
Fixed in [36b93d9](https://github.com/OldEnt/stellaris-habitat-start-amaryllis/commit/36b93d987792bc20cd5ab9a71f0207ced092bd73) and [9bbfda6](https://github.com/OldEnt/stellaris-habitat-start-amaryllis/commit/9bbfda61f2b5871f540a08734302c68f58bcdab3)
